# Generated by Django 4.2.1 on 2023-05-17 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Вид алкоголя')),
            ],
            options={
                'verbose_name': 'Вид алкоголя',
                'verbose_name_plural': 'Виды алкоголя',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Подвид алкоголя')),
                ('related_to_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menulist', verbose_name='Вид алкоголя')),
            ],
            options={
                'verbose_name': 'Подвид алкоголя',
                'verbose_name_plural': 'Подвиды алкоголя',
            },
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Закуска')),
                ('related_to_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menulist', verbose_name='Закуски')),
            ],
            options={
                'verbose_name': 'Закуска',
                'verbose_name_plural': 'Закуски',
            },
        ),
        migrations.CreateModel(
            name='Alcogol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название алкоголя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('related_to_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menulist', verbose_name='Вид алкоголя')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.type', verbose_name='Подвид алкоголя')),
            ],
            options={
                'verbose_name': 'Название алкоголя',
                'verbose_name_plural': 'Названия алкоголя',
            },
        ),
    ]
