# Generated by Django 4.2.1 on 2023-05-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulist',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='alcogol',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название алкоголя'),
        ),
        migrations.AlterField(
            model_name='menulist',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Вид алкоголя'),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Закуска'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Подвид алкоголя'),
        ),
    ]
