# Generated by Django 4.2.1 on 2023-05-27 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_alcogol_related_to_name_alter_alcogol_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Характеристика алкоголя')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Страна')),
                ('mark', models.CharField(blank=True, max_length=40, null=True, verbose_name='Торговая марка')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Обьем')),
                ('strength', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Крепость')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет')),
                ('sugar_supply', models.CharField(blank=True, default='нет', max_length=20, null=True, verbose_name='Содержание сахара')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.AddField(
            model_name='alcogol',
            name='characters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.characters'),
        ),
    ]
